### ISSUE TITLE
[TODO] Comments

### ISSUE THREAD

**Issue by ObserverOfTime** [mangadventure/MangAdventure#15]
- [ ] Comments on series
- [ ] Comments on chapters
- [ ] Links to comments
- [ ] Hiding spoilers
- [ ] Mentioning users?

These should be handled by the [framework](https://github.com/Radi85/Comment):

- [x] Markup (Markdown)
- [x] Restrict to users
- [x] Replying to comments
- [x] Editing comments
- [x] Deleting comments
- [x] Upvotes & downvotes?
