### ISSUE TITLE
[TODO] Revamp front-end

### ISSUE THREAD

**Issue by rainx0r** [mangadventure/MangAdventure#22]
The key goals of the front-end overhaul are to increase mobile friendliness, style the website to be more modern and optimize navigation.

Specific requirements of the new design that need to be met are:
- [ ] Library & Front Page Pagination

Task List:
- [ ] Redesign
  - [ ] Design Language (UI)
  - [ ] Page / Site Layout (UX)
  - [ ] Concrete Design Specification / Prototype in a Design & Prototyping tool (e.g. [Adobe XD](https://www.adobe.com/de/products/xd.html), [Figma](https://www.figma.com/), [Pencil](https://pencil.evolus.vn/))
- [ ] Reimplementation
  - [ ] Implementation of UI components
      - [ ] Might need a CSS framework like [Pico](https://github.com/picocss/pico)
  - [ ] Implementation of new layout
    - [ ] Might need increased XHR use or make use of ~~[Turbolinks](https://github.com/turbolinks/turbolinks)~~ [htmx](https://htmx.org)
