### ISSUE TITLE
[TODO] Reader improvements MK II

### ISSUE THREAD

**Issue by ObserverOfTime** [mangadventure/MangAdventure#23]
The reader will need to be rewritten once the redesign (#22) is completed.

Requirements:
* [ ] Series types (Manga/Comic/Webtoon/Novel)
* [ ] Reading modes
   * [ ] Right to left
   * [ ] Left to right
   * [ ] Long strip
   * [ ] Fit to screen
   * [ ] Double page
* [ ] 18+ series filter

The reader could use a [webpub manifest](https://readium.org/webpub-manifest/extensions/divina.html) generated based on the chapter to determine the default reading mode (RTL for manga, LTR for comics, TTB for webtoons) and request the pages via XHR.
The long strip mode may be used as the `noscript` fallback mode.

It must also recognize a query parameter which defines the page to start from.

For novels, we can just let the browser handle the PDF file.
