### ISSUE TITLE
[TODO] Rewrite API (v2)

### ISSUE THREAD

**Issue by ObserverOfTime** [mangadventure/MangAdventure#4]
- [x] Paginated results
- [x] Search & sort order filters
- [x] OpenAPI documentation
- [x] More privileges for staff & users
- [x] Rate limiting & API keys
- [x] Option to keep legacy API
